### PR TITLE
Install Java 8 JRE as well as Java 7 JRE and JDK

### PR DESCRIPTION
**Pull request by cb372**

### CODE REVIEW

**Comment by theefer** [comment]
(Why) do we want both?

**Comment by cb372** [comment]
Because Java 8, while preferred, is slightly dodgy because there is no Ubuntu Trusty package for it. (We have to do our own ghetto backporting and grab it from the Utopic repo.) So some teams might prefer to stick with Java 7 for now.

Ideal solution would be to upgrade our base image to the latest Ubuntu, but that's a big step. This is just a stopgap until that happens.

**Comment by theefer** [comment]
Would having different images per JDK version be excessive? I guess it might be (combinatorial explosion if we do that for multiple things)...

Seems like an antipattern to ship more versions/software than needed, but I suppose as long as it's clear which one you're using...

/cc @guardian/architects

**Comment by rrees** [comment]
My feeling would be one version per image but I'm not sure if there are any subtleties here.

**Comment by philwills** [comment]
Yea, I think one version per image makes sense. When I've moved to Utopic it hasn't been a big deal, but I wasn't doing any of the enhanced networking funkiness.

**Comment by cb372** [comment]
Had another go in #2

**Comment by cb372** [comment]
Superseded by #5

**Pull request closed without merging**
