### PR TITLE
Extend Packer file to build 2 images

### PR DESCRIPTION
**Pull request by cb372**
Third time's a charm!

@sihil @philwills

### CODE REVIEW

**Comment by philwills** [comment]
I'm kind of with @sihil in that I think if you want to use something from the Utopic repo, you might as well just use Utopic as the base. However, this still looks good and useful and you've been through enough iterations that I'd be tempted to merge this now and potentially come back to that later.

**Comment by philwills** [comment]
Also, I could have sworn something I work on regularly, I'd put onto Utopic/Java8, but I can't find any evidence of that.

**Comment by cb372** [comment]
@sihil is it ok to merge this, and deal with upgrading to Utopic in a separate PR? We (CAPI) would like to build and use a Java 8 image soon-ish. This pre-baked AMI would really speed up our deploys.

FWIW, we are already using the Utopic Java 8 package on Trusty on PROD with no problems. So I don't think there's much risk in doing this as a temporary measure.

**Comment by cb372** [comment]
Superseded by #5

**Pull request closed without merging**
