### PR TITLE
Self deployment scripts

### PR DESCRIPTION
**Pull request by sihil**
A modified version of the native packager scripts that provide self-deployment capabilities intended for Riff-Raff.

### CODE REVIEW

**Comment by philwills** [comment]
I can't help feeling that it's better to do much of this with http://www.scala-sbt.org/sbt-native-packager/formats/debian.html, but otherwise :+1:

**Comment by sihil** [comment]
I think in this case reinstalling a package using a systemd config that was provided by the package might not work so well. But generally I do think that we should seriously consider switching towards packages.

**Comment by philwills** [comment]
True, I hadn't thought that through.

**Pull request merged**
